name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: composer install
      uses: nick-zh/composer@php7.4
      with:
        action: install

      - name: codeception run
      uses: joelwmale/codeception-action@1.0.0
