name: Codeception

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        uses: nick-zh/composer@php7.4
        with:
          action: install --ignore-platform-reqs
      - name: codeception run
        uses: joelwmale/codeception-action@1.0.0
