name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action@master
        with:
          args: validate

      - name: composer install
        uses: MilesChou/composer-action@master
        with:
          args: install
