name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: root
        run: pwd
      - name: list
        run: ls -lash
      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action/7.4/install@master
        with:
          args: validate
  build:
    runs-on: ubuntu-latest
    steps:
      - name: composer install
        uses: MilesChou/composer-action/7.4/install@master
        with:
          args: install
