name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action/7.4/install@master
        with:
          args: validate
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        uses: MilesChou/composer-action/7.4/install@master
        with:
          args: install --ignore-platform-reqs --no-progress
  composer-unused:
    runs-on: ubuntu-latest
    steps:
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          extensions: zip, gd
      - uses: actions/checkout@v2
      - name: composer install
        uses: MilesChou/composer-action/7.4/install@master
        with:
          args: install --ignore-platform-reqs
      - name: composer unused
        run: curl -JOL https://github.com/icanhazstring/composer-unused/releases/latest/download/composer-unused.phar && php composer-unused.phar --no-cache --no-interaction --no-progress
